plugins {
    id 'java'
    id 'idea'
}

idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}

group 'course.dml'
version '1.0-SNAPSHOT'
sourceCompatibility = '1.8'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.apache.spark:spark-sql_2.12:3.5.5'
    implementation 'org.apache.spark:spark-mllib_2.12:3.5.5'
    testImplementation group: 'junit', name: 'junit', version: '4.13.2'
}
