plugins {
    id 'java'
}

group = 'course.spring'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.apache.spark:spark-sql_2.12:3.5.5'
    implementation 'org.apache.spark:spark-mllib_2.12:3.5.5'
    testImplementation platform('org.junit:junit-bom:5.9.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}
